title: H&M recommendation

remote_theme: pmarsceill/just-the-docs # Borrowing the theme from https://github.com/pmarsceill/just-the-docs
github_repo_url: "https://github.com/esterigle/prova" 

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page. (true or false)
heading_anchors: true

# Activate a "Back to top" link
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Raquel Domínguez, Ester Iglesias i Ana Berta Vegas."

aux_links:
  "Obrir el projecte a GitHub":
    - "https://github.com/esterigle/prova"

# Include plugins for relative links and a remote theme
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

# search_enabled: false
